three_digit_heading_text = "4.1.1   Test & something 4.1.1 else      here   4.1.1   Maybe?"
three_digit_heading_expected = "### Test & something 4.1.1 else      here   4.1.1   Maybe?"
two_digit_heading_text = "4.1   Test & something 4.1 else      here   4.1   Maybe?"
two_digit_heading_expected = "## Test & something 4.1 else      here   4.1   Maybe?"
one_digit_heading_text ="4   Test & something 4. else      here   4   Maybe?"
one_digit_heading_expected ="# Test & something 4. else      here   4   Maybe?"
no_digit_heading_text = " Test & something else   .   here   . .   Maybe?"
